spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mybatis?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  mvc:
    view:
#    页面默认前缀目录
      prefix: /WEB-INF/jsp/
#      页面默认后缀目录
      suffix: .jsp

  jpa:
    properties:
      hibernate:
        hbm2ddl:
        auto: create
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
  servlet:
    context-path: /spboot01


